PREFIX : <https://ns.volunteeringdata.io/>
PREFIX text: <http://jena.apache.org/text#>

CONSTRUCT {
	?activity
		:activityTitle ?activityTitle ;
		:activityDescription ?activityDescription ;
		:activityOrganisation ?organisation ;
	.

	?organisation 
		:organisationName ?organisationName ;
		:organisationDescription ?organisationDescription ;
	.
}
WHERE {
	(?activity ?activity_search_score) text:query (:activityDescription :activityTitle $activityQuery) .
	(?organisation ?organisation_search_score) text:query (:organisationDescription :organisationName $organisationQuery) .

	?activity
		:activityTitle ?activityTitle ;
		:activityDescription ?activityDescription ;
		:activityOrganisation ?organisation ;
	.

	?organisation 
		:organisationName ?organisationName ;
		:organisationDescription ?organisationDescription ;
	.
}
ORDER BY DESC(?activity_score) DESC(?organisation_score)
