BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>

SELECT *
WHERE {
    ?option
        :optionDisplayName ?displayName ;
        :optionApp ?app ;
    .

    OPTIONAL { ?option :optionIcon ?icon .}
}
