BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>
PREFIX text: <http://jena.apache.org/text#>

SELECT ?organisation ?organisation_name ?search_match ?search_score
WHERE {
  (?organisation ?search_score ?search_match) text:query (:organisationName :organisationDescription $query "highlight:s:<mark>|e:</mark>") .
  
  ?organisation :organisationName ?organisation_name .
}
ORDER BY DESC(?search_score)
