BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>
PREFIX text: <http://jena.apache.org/text#>

CONSTRUCT {
    <Organisations> :organisations ?organisation .

    ?organisation
        :organisationName ?name ;
        :indexMatchingScore ?score ;
    .
}
WHERE {
    (?organisation ?score ?value) text:query (:organisationName $name) .
    ?organisation :organisationName ?name .
}
