BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>
PREFIX text: <http://jena.apache.org/text#>

CONSTRUCT {
    <Organisations> :organisations ?organisation .

    ?organisation
        :label ?label ;
        :indexMatchingScore ?score ;
    .
}
WHERE {
    (?organisation ?score ?value) text:query (:organisationLabel $name) .
    ?organisation :label ?label .
}
