BASE                    <https://id.volunteeringdata.io/>

PREFIX id:              <https://id.volunteeringdata.io/>
PREFIX :                <https://id.volunteeringdata.io/schema/>

PREFIX units:           <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX spatialF:        <http://jena.apache.org/function/spatial#>
prefix xsd:             <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {
    <Activities> :activities ?activity_id .

    ?activity_id
        :distanceFromSearchLocation ?activity_distance_from_search_location ;
        :title ?activity_name ;
        :description ?activity_description ;
        :organisation ?organisation_id ;
        :session ?session ;
        :role ?role_id ;
    .

    ?organisation_id
        :name ?organisation_name ;
        :description ?organisation_description ;
        :cause ?cause_id ;
    .

    ?cause_id
        :label ?cause_label ;
    .

    ?session
        :location ?location ;
    .

    ?location 
        :latitude ?activity_latitude ;
        :longitude ?activity_longitude ;
    .

    ?role_id
        :title ?role_title ;
        :description ?role_description ;
        :applyLink ?role_apply_link ;
        :requirement ?requirement_id ;
    .

    ?requirement_id
        :label ?requirement_label ;
    .
}
WHERE
{
    ?session
        :location ?location ;
    .

    ?location 
        :latitude ?activity_latitude ;
        :longitude ?activity_longitude ;
    .

    BIND(spatialF:convertLatLon(?activity_latitude, ?activity_longitude) as ?activity_location)
    BIND(spatialF:convertLatLon($lat, $lon) as ?search_location)

    FILTER(spatialF:nearby(?activity_location, ?search_location, $within, units:metre))

    BIND(spatialF:distance(?activity_location, ?search_location, units:metre) as ?activity_distance_from_search_location)

    ?activity_id
        :title ?activity_name ;
        :description ?activity_description ;
        :organisation ?organisation_id ;
        :session ?session ;
        :role ?role_id ;
    .

    ?organisation_id :name ?organisation_name .

    OPTIONAL { ?organisation_id :description ?organisation_description . }

    OPTIONAL {
        ?organisation_id :cause ?cause_id .
        ?cause_id :label ?cause_label .
    }

    OPTIONAL { ?role_id :title ?role_title . }
    OPTIONAL { ?role_id :description ?role_description . }
    OPTIONAL { ?role_id :applyLink ?role_apply_link . }
    OPTIONAL {
        ?role_id :requirement ?requirement_id .
        OPTIONAL { ?requirement_id :label ?requirement_label . }
    }
}
