BASE                    <https://id.volunteeringdata.io/>

PREFIX id:              <https://id.volunteeringdata.io/>
PREFIX :                <https://ns.volunteeringdata.io/>

PREFIX units:           <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX spatialF:        <http://jena.apache.org/function/spatial#>
prefix xsd:             <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {
    <Activities> :activities ?activity .

    ?activity
        a :Activity ;
        :distanceFromSearchLocation ?activity_distance_from_search_location ;
        :title ?activity_title ;
        :description ?activity_description ;
        :requiresEmergencyParticipation ?activity_requires_emergency_participation ;
        :organisation ?organisation ;
        :session ?session ;
        :role ?role ;
    .

    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
        :description ?organisation_description ;
        :website ?organisation_website ;
        :charityNumber ?organisation_charity_number ;
        :cause ?cause ;
    .

    ?cause
        a :Cause ;
        :label ?cause_label ;
    .

    ?session
        a :Session ;
        :location ?location ;
        :time ?time ;
    .

    ?location
        a :Location ;
        :name ?location_name ;
        :address ?location_address ;
        :latitude ?activity_latitude ;
        :longitude ?activity_longitude ;
    .

    ?time 
        a :Time ;
        :label ?time_label ;
    .

    ?role
        a :Role ;
        :title ?role_title ;
        :description ?role_description ;
        :applyLink ?role_apply_link ;
        :requirement ?requirement ;
    .

    ?requirement
        a :Requirement ;
        :label ?requirement_label ;
    .

    ?skill
         a :Skill ;
         :label ?skill_label ;
    .
}
WHERE
{
    ?session
        :location ?location ;
    .

    ?location 
        :latitude ?activity_latitude ;
        :longitude ?activity_longitude ;
    .

    BIND(spatialF:convertLatLon(?activity_latitude, ?activity_longitude) as ?activity_location)
    BIND(spatialF:convertLatLon($lat, $lon) as ?search_location)

    FILTER(spatialF:nearby(?activity_location, ?search_location, $distance, units:metre))

    BIND(spatialF:distance(?activity_location, ?search_location, units:metre) as ?activity_distance_from_search_location)

    OPTIONAL { ?location :name ?location_name . }
    OPTIONAL { ?location :address ?location_address . }

    ?activity
        :session ?session ;
        :title ?activity_title ;
        :organisation ?organisation ;
    .

    ?organisation :name ?organisation_name .

    OPTIONAL { ?organisation :description ?organisation_description . }
    OPTIONAL { ?organisation :website ?organisation_website . }
    OPTIONAL { ?organisation :charityNumber ?organisation_charity_number . }

    OPTIONAL {
        ?organisation :cause ?cause .
        ?cause :label ?cause_label .
    }

    OPTIONAL { ?activity :description ?activity_description . }

    OPTIONAL { ?activity :requiresEmergencyParticipation ?activity_requires_emergency_participation . }

    OPTIONAL { ?location :name ?location_name . }
    OPTIONAL { ?location :address ?location_address . }

    OPTIONAL {
        ?session :time ?time .

        OPTIONAL { ?time :label ?time_label . }
    }

    OPTIONAL {
        ?activity :role ?role .
        OPTIONAL { ?role :title ?role_title . }
        OPTIONAL { ?role :description ?role_description . }
        OPTIONAL { ?role :applyLink ?role_apply_link . }
        OPTIONAL {
            ?role :requirement ?requirement .
            ?requirement :label ?requirement_label .
        }
        OPTIONAL {
            ?role :skill ?skill .
            ?skill :label ?skill_label .
        }
    }
}
ORDER BY ?activity_distance_from_search_location
