BASE            <https://id.volunteeringdata.io/>
PREFIX :        <https://ns.volunteeringdata.io/>
PREFIX id:      <https://id.volunteeringdata.io/>
prefix skos:    <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
        :description ?organisation_description ;
        :website ?organisation_website ;
        :charityNumber ?organisation_charity_number ;
        :image ?organisation_image ;
        :cause ?cause  ;
        :activity ?activity ;
    .

    ?cause skos:prefLabel ?cause_label .

    ?activity :title ?activity_title .
}
WHERE {
    ?organisation
        :organisationName ?organisation_name ;
        :organisationActivity ?activity ;
    .

    OPTIONAL { ?organisation :organisationDescription ?organisation_description . }
    OPTIONAL { ?organisation :organisationWebsite ?organisation_website . }
    OPTIONAL { ?organisation :organisationCharityNumber ?organisation_charity_number . }
    OPTIONAL { ?organisation :organisationImage ?organisation_image . }

    OPTIONAL {
        ?organisation :organisationCause ?cause .
        ?cause skos:prefLabel ?cause_label .
    }

    ?activity :title ?activity_title .
}
