BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>
PREFIX id: <https://id.volunteeringdata.io/>

CONSTRUCT {
    <Organisations> :organisations ?organisation .

    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
        :description ?organisation_description ;
        :website ?organisation_website ;
        :charityNumber ?organisation_charity_number ;
        :cause ?cause  ;
        :activity ?activity ;
    .

    ?cause :label ?cause_label .

    ?activity :title ?activity_title .
}
WHERE {
    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
    .

    OPTIONAL { ?organisation :description ?organisation_description . }
    OPTIONAL { ?organisation :website ?organisation_website . }
    OPTIONAL { ?organisation :charityNumber ?organisation_charity_number . }

    OPTIONAL {
        ?organisation :cause ?cause .
        ?cause :label ?cause_label .
    }

    ?activity :title ?activity_title .
}
