BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>

CONSTRUCT {
    <Requirement> :requirements ?requirement .

    ?requirement
        :label ?label ;
    .
}
WHERE {
    ?requirement
        a :Requirement ;
        :label ?label ;
    .
}
