BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>

CONSTRUCT {
    <Organisations> :organisations ?organisation .
    ?organisation :label ?organisationLabel .
}
WHERE {
    ?organisation :organisationLabel ?organisationLabel .
}
