BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>
PREFIX id: <https://id.volunteeringdata.io/>

CONSTRUCT {
    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
        :description ?organisation_description ;
        :website ?organisation_website ;
        :charityNumber ?organisation_charity_number ;
        :cause ?cause  ;
        :activity ?activity ;
    .

    ?cause :label ?cause_label .

    ?activity
        :title ?activity_title ;
        :description ?activity_description ;
        :session ?session ;
        :role ?role ;
    .

    ?session
        :location ?location ;
        :time ?time ;
    .

    ?location
        :name ?location_name ;
        :address ?location_address ;
        :latitude ?activity_latitude ;
        :longitude ?activity_longitude ;
    .

    ?time :label ?time_label .

    ?role
        :title ?role_title ;
        :description ?role_description ;
        :applyLink ?role_apply_link ;
        :requirement ?requirement ;
    .

    ?requirement :label ?requirement_label .
}
WHERE {
    FILTER(?organisation = IRI($id))

    ?organisation
        a :Organisation ;
        :name ?organisation_name ;
        :activity ?activity ;
    .

    OPTIONAL { ?organisation :description ?organisation_description . }
    OPTIONAL { ?organisation :website ?organisation_website . }
    OPTIONAL { ?organisation :charityNumber ?organisation_charity_number . }

    OPTIONAL {
        ?organisation :cause ?cause .
        ?cause :label ?cause_label .
    }

    ?activity :title ?activity_title .

    OPTIONAL { ?activity :description ?activity_description . }

    OPTIONAL {
        ?activity :session ?session .
        OPTIONAL {
            ?session :location ?location .

            ?location 
                :latitude ?activity_latitude ;
                :longitude ?activity_longitude ;
            .

            OPTIONAL { ?location :name ?location_name . }
            OPTIONAL { ?location :address ?location_address . }
        }
        OPTIONAL {
            ?session :time ?time .

            OPTIONAL { ?time :label ?time_label . }
        }
    }

    OPTIONAL {
        ?activity :role ?role .
        OPTIONAL { ?role :title ?role_title . }
        OPTIONAL { ?role :description ?role_description . }
        OPTIONAL { ?role :applyLink ?role_apply_link . }
        OPTIONAL {
            ?role :requirement ?requirement .
            ?requirement :label ?requirement_label .
        }
    }
}
