# Volunteering vocabulary

## Namespaces
### Ontology Base URI
prefix :                <https://ns.volunteeringdata.io/>
prefix dc:              <http://purl.org/dc/terms/>
prefix geo:             <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix geosparql:       <http://www.opengis.net/ont/geosparql#>
prefix og:              <http://ogp.me/ns#>
prefix owl:             <http://www.w3.org/2002/07/owl#>
prefix rdf:             <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:            <http://www.w3.org/2000/01/rdf-schema#>
prefix skos:            <http://www.w3.org/2004/02/skos/core#>
prefix time:            <http://www.w3.org/2006/time#>
prefix vann:            <http://purl.org/vocab/vann/>
prefix vcard:           <http://www.w3.org/2006/vcard/ns#>
prefix xsd:             <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {

<https://ns.volunteeringdata.io/>
    a owl:Ontology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Volunteering and Social Action Ontology"@en ;
    dc:title "Volunteering and Social Action Ontology"@en ;
    dc:description "Defines a vocabulary to describe volunteering activities, volunteer-involving organisations and volunteering management systems."@en ;
    dc:issued "2025-11-20"^^xsd:date ;
    owl:versionIRI <https://ns.volunteeringdata.io/> ;
    owl:versionInfo "2026-03-12" ;
    vann:preferredNamespacePrefix "volunteering" ;
    vann:preferredNamespaceUri "https://ns.volunteeringdata.io/"^^xsd:anyURI ;
    rdfs:seeAlso <https://standard.volunteeringdata.io/ontology/> ;
.


### Object Properties
:activity
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Activity ;
    rdfs:label "has activity"@en ;
.

:location
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf geo:location ;
    rdfs:range :Location ;
    rdfs:label "has location"@en ;
.

:organisation
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Organisation ;
    rdfs:label "has organisation"@en ;
.

:relatedConcept
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range skos:Concept ;
    rdfs:label "has related concept"@en ;
.

:role
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Role ;
    rdfs:label "has role"@en ;
.

:session
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Session ;
    rdfs:label "has session"@en ;
.

:time
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Time ;
    rdfs:label "has time"@en ;
.


## Datatype Properties
:address
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has address"@en ;
.

:allowsRemoteParticipation
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "allows remote participation"@en ;
.

:applyLink
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has apply link"@en ;
.

:charityNumber
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has charity number"@en ;
.

:commitment
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has commitment"@en ;
    rdfs:comment "Free text description of the expected commitment to the role (e.g. 4 hours per week)."@en ;
.

:description
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf dc:description ;
    rdfs:label "has description"@en ;
.

:geometry
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf geosparql:hasGeometry ;
    rdfs:label "has Geometry"@en ;
    rdfs:comment "A geometry represents the spatial extent of a location (see OGC GeoSPARQL)."@en ;
    rdfs:seeAlso <https://opengeospatial.github.io/ogc-geosparql/> ;
.

:image
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf og:image ;
    rdfs:label "has Image"@en ;
    rdfs:comment "An image URL which can be used to present something related to volunteering."@en ;
    rdfs:seeAlso <https://opengeospatial.github.io/ogc-geosparql/> ;
.

:latitude
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf geo:lat ;
    rdfs:label "has latitude"@en ;
    rdfs:comment "The WGS84 latitude of a SpatialThing in decimal degrees (see WGS84 Geo Positioning)."@en ;
    rdfs:seeAlso <https://www.w3.org/2003/01/geo/wgs84_pos> ;
.

:longitude
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf geo:long ;
    rdfs:label "has longitude"@en ;
    rdfs:comment "The WGS84 longitude of a SpatialThing in decimal degrees (see WGS84 Geo Positioning)."@en ;
    rdfs:seeAlso <https://www.w3.org/2003/01/geo/wgs84_pos> ;
.

:maximumAge
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has maximum age"@en ;
.

:minimumAge
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has minimum age"@en ;
.

:name
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has name"@en ;
.

:requiresEmergencyParticipation
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "requires emergency participation"@en ;
.

:title
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has title"@en ;
.

:website
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "has website"@en ;
.

:Activity
    a owl:Class ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Activity"@en ;
    rdfs:comment "Any kind of activity that involves volunteers."@en ;
    dc:description "Volunteering Activity"@en ;
.

### Object Properties
:activityOrganisation
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :organisation ;
    owl:inverseOf :organisationActivity ;
    rdfs:domain :Activity ;
    rdfs:range :Organisation ;
    rdfs:label "activity has organisation"@en ;
.

:activityRole
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :role ;
    owl:inverseOf :roleActivity ;
    rdfs:domain :Activity ;
    rdfs:range :Role ;
    rdfs:label "activity has role"@en ;
.

:activitySession
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :session ;
    owl:inverseOf :sessionActivity ;
    rdfs:domain :Activity ;
    rdfs:range :Session ;
    rdfs:label "activity has session"@en ;
.


### Datatype Properties
:activityTitle
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :title ;
    rdfs:domain :Activity ;
    rdfs:label "activity has title"@en ;
.

:activityDescription
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :description ;
    rdfs:domain :Activity ;
    rdfs:label "activity has description"@en ;
.

:activityImage
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :image ;
    rdfs:domain :Activity ;
    rdfs:label "activity has image"@en ;
.

:activityRequiresEmergencyParticipation
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :requiresEmergencyParticipation ; 
    rdfs:domain :Activity ;
    rdfs:range xsd:boolean ;
    rdfs:label "activity requires emergency participation"@en ;
.

:Location
    a owl:Class ;
    rdfs:subClassOf geo:SpatialThing, geosparql:SpatialObject ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Location"@en ;
    rdfs:comment "Any location related to volunteering activities."@en ;
    dc:description "Volunteering Activity Location"@en ;
.


### Object Properties
:locationSession
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:domain :Location ;
    rdfs:range :Session ;
    rdfs:label "session has location"@en ;
.


### Datatype Properties
:locationName
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :name ;
    rdfs:domain :Location ;
    rdfs:label "location has name"@en ;
.

:locationAddress
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :address ;
    rdfs:domain :Location ;
    rdfs:label "location has address"@en ;
.

:locationGeometry
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :geometry ;
    rdfs:domain :Location ;
    rdfs:label "location has Geometry"@en ;
.

:locationLatitude
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :latitude ;
    rdfs:domain :Location ;
    rdfs:label "location has latitude"@en ;
.

:locationLongitude
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :longitude ;
    rdfs:domain :Location ;
    rdfs:label "location has longitude"@en ;
.

:Organisation
    a owl:Class ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Organisation"@en ;
    rdfs:comment "Any organisation running activities that involve volunteers."@en ;
    dc:description "Volunteer-Involving Organisation"@en ;
.


# Object Properties
:organisationActivity
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :activity ;
    owl:inverseOf :activityOrganisation ;
    rdfs:domain :Organisation ;
    rdfs:range :Activity ;
    rdfs:label "organisation has activity"@en ;
.

:organisationCause
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :cause ;
    owl:inverseOf :causeOrganisation ;
    rdfs:domain :Organisation ;
    rdfs:range :Cause ;
    rdfs:label "organisation has charitable cause"@en ;
.


# Datatype Properties
:organisationName
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :name ;
    rdfs:domain :Organisation ;
    rdfs:label "organisation has name"@en ;
.

:organisationDescription
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :description ;
    rdfs:domain :Organisation ;
    rdfs:label "organisation has description"@en ;
.

:organisationImage
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :image ;
    rdfs:domain :Organisation ;
    rdfs:label "organisation has image"@en ;
.

:organisationWebsite
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :website ;
    rdfs:domain :Organisation ;
    rdfs:label "organisation has website"@en ;
.

:organisationCharityNumber
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :charityNumber ;
    rdfs:domain :Organisation ;
    rdfs:label "organisation has charity number"@en ;
.

:Role
    a owl:Class ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Role"@en ;
    rdfs:comment "Any kind of role related to a volunteering activity."@en ;
    dc:description "Volunteering Role"@en ;
.

### Object Properties
:roleAccessibility
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :accessibility ;
    owl:inverseOf :accessibilityRole ;
    rdfs:domain :Role ;
    rdfs:range :Accessibility ;
    rdfs:label "role has accessibility"@en ;
.

:roleActivity
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :activity ;
    owl:inverseOf :activityRole ;
    rdfs:domain :Role ;
    rdfs:range :Activity ;
    rdfs:label "role has activity"@en ;
.

:roleRequirement
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :requirement ;
    owl:inverseOf :requirementRole ;
    rdfs:domain :Role ;
    rdfs:range :Requirement ;
    rdfs:label "role has requirement"@en ;
.

:roleReward
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :reward ;
    owl:inverseOf :rewardRole ;
    rdfs:domain :Role ;
    rdfs:range :Reward ;
    rdfs:label "role has reward"@en ;
.

:roleSkill
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :skill ;
    owl:inverseOf :skillRole ;
    rdfs:domain :Role ;
    rdfs:range :Skill ;
    rdfs:label "role has skill"@en ;
.


### Datatype Properties
:roleAllowsRemoteParticipation
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :allowsRemoteParticipation ; 
    rdfs:domain :Role ;
    rdfs:range xsd:boolean ;
    rdfs:label "role allows remote participation"@en ;
.

:roleApplyLink
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :applyLink ;
    rdfs:domain :Role ;
    rdfs:label "role has apply link"@en ;
.

:roleCommitment
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :commitment ;
    rdfs:domain :Role ;
    rdfs:label "role has commitment"@en ;
.

:roleDescription
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :description ;
    rdfs:domain :Role ;
    rdfs:label "role has description"@en ;
.

:roleMaximumAge
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :maximumAge ;
    rdfs:domain :Role ;
    rdfs:label "role has maximum age"@en ;
.

:roleMinimumAge
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :minimumAge ;
    rdfs:domain :Role ;
    rdfs:label "role has minimum age"@en ;
.

:roleTitle
    a owl:DatatypeProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :title ;
    rdfs:domain :Role ;
    rdfs:label "role has title"@en ;
.

:Session
    a owl:Class ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Session"@en ;
    rdfs:comment "A session describes a time and place for an activity that involves volunteers."@en ;
    dc:description "Volunteering Activity Session"@en ;
.

### Object Properties
:sessionActivity
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :activity ;
    owl:inverseOf :activitySession ;
    rdfs:domain :Session ;
    rdfs:range :Activity ;
    rdfs:label "session has activity"@en ;
.

:sessionLocation
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :location ;
    owl:inverseOf :locationSession ;
    rdfs:domain :Session ;
    rdfs:range :Location ;
    rdfs:label "session has location"@en ;
.

:sessionTime
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :time ;
    owl:inverseOf :timeSession ;
    rdfs:domain :Session ;
    rdfs:range :Time ;
    rdfs:label "session has time"@en ;
.


:Taxonomy
    a skos:ConceptScheme ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:hasTopConcept :Accessibility, :Cause, :Requirement, :Reward, :Skill ;
    rdfs:label "Taxonomy"@en ;
    dc:title "Volunteering Taxonomy"@en ;
    dc:description "The taxonomy of concepts related to volunteering activities."@en ;
.


### Super property
:relatedConcept
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:range :Concept ;
    rdfs:label "has related concept"@en ;
.


### Object Properties
:accessbibility
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :relatedConcept ;
    rdfs:label "has accessibility information"@en ;
.

:accessibilityRole
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :role ;
    owl:inverseOf :roleAccessibility ;
    rdfs:domain :Accessibility ;
    rdfs:range :Role ;
    rdfs:label "accessibility information has role"@en ;
.

:cause
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :relatedConcept ;
    rdfs:label "has cause"@en ;
.

:causeOrganisation
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :organisation ;
    owl:inverseOf :organisationCause ;
    rdfs:domain :Cause ;
    rdfs:range :Organisation ;
    rdfs:label "charitable cause has organisation"@en ;
.

:requirement
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :relatedConcept ;
    rdfs:label "has requirement"@en ;
.

:requirementRole
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :role ;
    owl:inverseOf :roleRequirement ;
    rdfs:domain :Requirement ;
    rdfs:range :Role ;
    rdfs:label "requirement has role"@en ;
.

:reward
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :relatedConcept ;
    rdfs:label "has reward"@en ;
.

:rewardRole
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :role ;
    owl:inverseOf :roleReward ;
    rdfs:domain :Reward ;
    rdfs:range :Role ;
    rdfs:label "reward has role"@en ;
.

:skill
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :relatedConcept ;
    rdfs:label "has skill"@en ;
.

:skillRole
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :role ;
    owl:inverseOf :roleSkill ;
    rdfs:domain :Skill ;
    rdfs:range :Role ;
    rdfs:label "skill has role"@en ;
.

:Time
    a owl:Class ;
    rdfs:subClassOf time:TemporalEntity ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Time"@en ;
    rdfs:comment "Any time information related to volunteering activities modeled as a OWL time temporal entity."@en ;
    dc:description "Volunteering Activity Time Information"@en ;
.

:WeekdayTimePeriod
    a owl:Class ;
    rdfs:subClassOf :Time ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:comment "A predefined time period within a specific day of the week (morning, afternoon or evening)."@en ;
    rdfs:label "Weekday Time Period"@en ;
.

### Object Properties
:timeSession
    a owl:ObjectProperty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:subPropertyOf :session ;
    owl:inverseOf :sessionTime ;
    rdfs:domain :Time ;
    rdfs:range :Session ;
    rdfs:label "time has session"@en ;
.


## Predefined Temporal Entities
:MondayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Monday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:MondayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Monday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:MondayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Monday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Monday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:TuesdayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Tuesday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:TuesdayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Tuesday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:TuesdayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Tuesday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Tuesday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:WednesdayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Wednesday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:WednesdayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Wednesday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:WednesdayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Wednesday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Wednesday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:ThursdayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Thursday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:ThursdayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Thursday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:ThursdayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Thursday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Thursday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:FridayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Friday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:FridayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Friday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:FridayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Friday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Friday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SaturdayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Saturday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SaturdayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Saturday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SaturdayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Saturday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Saturday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SundayMorning
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Sunday morning"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "6"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SundayAfternoon
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Sunday afternoon"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "12"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:SundayEvening
    a time:TemporalEntity, :Time, :WeekdayTimePeriod ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    rdfs:label "Sunday evening"@en ;
    time:hasBeginning [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "18"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
    time:hasEnd [
        a time:Instant ;
        time:inDateTime [
            a time:GeneralDateTimeDescription ;
            time:dayOfWeek time:Sunday ;
            time:hour "24"^^xsd:nonNegativeInteger ;
            time:minute "0"^^xsd:nonNegativeInteger ;
            time:second "0"^^xsd:nonNegativeInteger ;
        ] ;
    ] ;
.

:Accessibility
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:topConceptOf :Taxonomy ;
    skos:prefLabel "Accessibility"@en ;
    skos:definition "Any accessibility information related to volunteering activities."@en ;
.


### Taxonomy Hierarchy
:AgeRequirements
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :Taxonomy ;
    skos:prefLabel "Age Requirements" ;
    skos:definition "Any information regarding specific ages or ranges of ages required or disallowed from a activity." ;
.

:DigitalAccessibility
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :Taxonomy ;
    skos:prefLabel "Digital Accessibility"@en ;
    skos:definition "Any accessbility information regarding digital requirements for an activity"@en ;
.

:ExpensesPaid
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :Taxonomy ;
    skos:prefLabel "Expenses Paid" ;
    skos:definition "Any information regarding reimbursement for activity or role-related expenses.";
.

:LanguageRequirements
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :Taxonomy ;
    skos:prefLabel "Language Requirements" ;
    skos:definition "Any language information for an activity, including required language(s) and translation services available." ;
.

:PhysicalAccessibility
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :Taxonomy ;
    skos:prefLabel "Physical Accessibility"@en ;
    skos:definition "Any accessbibility information regarding physical ability required for an activity" ;
.


##Digital Accessibility Concepts
:WifiUsage
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :DigitalAccessibility ;
    skos:prefLabel "Wifi Usage" ;
    skos:definition "Any information on wifi usage necessary for a activity." ;
.

:TechnologyRequirements
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :DigitalAccessibility ;
    skos:prefLabel "Technology Requirements" ;
    skos:definition "Any information on devices (laptop, phone, smartphone) and software required for a activity." ;
.

:TechnologyAvailability
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :DigitalAccessibility ;
    skos:prefLabel "Technology Availability" ;
    skos:definition "Any information on supplementory accessiblity software available in activities (screen readers, captioning)." ;
.


##Physical Accessibility Concepts
:RemoteAccessibility
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Remote Accessibility" ;
    skos:definition "Any accomodations available for remote participation in an activity." ;
.

:BuildingAccessibilityFeatures
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Building Accessibility Features" ;
    skos:definition "Any information on building accessibility features for mobility aid users and accessible gender, faith, etc. rooms." ;
.

:PublicTransportAccess
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Public Transport Access" ;
    skos:definition "Any information on venue access via public transport lines." ;
.

:ParkingAvailability
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Parking Availability" ;
    skos:definition "Any information on parking availability and accessibility at the venue." ;
.

:ServiceAnimals
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Service Animals" ;
    skos:definition "Accessiblity information regarding usage of service animals in and around venue." ;
.

:VisualImpairment
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Visual Impairment" ;
    skos:definition "Any information on activities wherin visual impairments may be affected or accommodated." ;
.

:CareProfessionals
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:broader :Accessibility ;
    skos:inScheme :PhysicalAccessibility ;
    skos:prefLabel "Care Professionals" ;
    skos:definition "Any accommodations available for volunteers assisted by care professionals." ;
.

:Cause
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:topConceptOf :Taxonomy ;
    skos:prefLabel "Cause"@en ;
    skos:definition "Any charitable cause related to volunteering activities."@en ;
.


## Cause Concepts
:AnimalWelfare
    a skos:Concept ;
    skos:prefLabel "Animal Welfare"@en ;
    skos:altLabel "Wildlife"@en, "Pets"@en, "Creatures"@en, "Mammals"@en ;
    skos:definition "Volunteering focused on the protection, care, and welfare of animals, including wildlife conservation, pet support, and creature advocacy."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:AntiPoverty
    a skos:Concept ;
    skos:prefLabel "Anti-Poverty"@en ;
    skos:altLabel "Poverty Reduction"@en, "Tackling Poverty"@en ;
    skos:definition "Volunteering activities aimed at reducing poverty, supporting low-income households, and promoting economic empowerment."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ArtsAndCulture
    a skos:Concept ;
    skos:prefLabel "Arts and Culture"@en ;
    skos:altLabel "Culture"@en, "Society"@en, "Humanities"@en, "Music"@en, "Theatre"@en, "Dance"@en, "Graphic Arts"@en, "Crafts"@en ;
    skos:definition "Volunteering in artistic and cultural domains including music, theatre, dance, visual arts, crafts, and heritage preservation."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Care
    a skos:Concept ;
    skos:prefLabel "Care"@en ;
    skos:altLabel "Care Services"@en, "Care Providers"@en, "Counselling Support"@en, "Addiction Support"@en, "Social Care"@en, "Carers"@en, "Caregivers"@en, "Guardians"@en, "Live in carers"@en, "Home Carers"@en ;
    skos:definition "Volunteering providing care services, support to carers, counselling, and social care assistance."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CivilRights
    a skos:Concept ;
    skos:prefLabel "Civil Rights"@en ;
    skos:altLabel "Human Rights"@en, "Citizens Rights"@en, "Equality"@en, "Justice"@en ;
    skos:definition "Volunteering promoting human rights, civil liberties, equality, justice, and citizen empowerment."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Community
    a skos:Concept ;
    skos:prefLabel "Community"@en ;
    skos:altLabel "Community groups"@en, "Society"@en, "Local Public"@en ;
    skos:definition "Volunteering supporting community development, local initiatives, and strengthening of community groups."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CrimeSafety
    a skos:Concept ;
    skos:prefLabel "Crime / Safety"@en ;
    skos:altLabel "Protection"@en, "Security"@en, "Offences"@en, "Wrongdoing"@en ;
    skos:definition "Volunteering supporting crime prevention, public safety, victim support, and protection services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CrimeExOffenders
    a skos:Concept ;
    skos:prefLabel "Crime & ex-offenders"@en ;
    skos:altLabel "Criminal Justice System"@en, "Prisons"@en ;
    skos:definition "Volunteering supporting offenders, ex-offenders, rehabilitation programmes, and the criminal justice system."@en ;
    skos:broader :CrimeSafety ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:DevelopmentEmergencyRelief
    a skos:Concept ;
    skos:prefLabel "Development & emergency relief"@en ;
    skos:altLabel "Disaster emergency relief"@en, "Emergency Services"@en, "Emergency Support"@en, "Rescue Services"@en, "Responders"@en, "Natural Disasters"@en, "Urgent problem"@en, "Accidents"@en, "Tragedy"@en, "Crisis"@en ;
    skos:definition "Volunteering in emergency response, disaster relief, humanitarian aid, and crisis management."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Disability
    a skos:Concept ;
    skos:prefLabel "Disability"@en ;
    skos:altLabel "Disabled People"@en, "Diabled Groups"@en, "Impairment"@en ;
    skos:definition "Volunteering supporting people with disabilities, accessibility advocacy, and disability services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:EducationLanguages
    a skos:Concept ;
    skos:prefLabel "Education & languages"@en ;
    skos:altLabel "Schooling"@en, "Further Education"@en, "Tongues"@en, "Dialects"@en ;
    skos:definition "Volunteering in education programmes, language support, literacy, and educational development."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Environment
    a skos:Concept ;
    skos:prefLabel "Environment"@en ;
    skos:altLabel "Natural World"@en, "Surroundings"@en, "Nature"@en, "Planet"@en, "Conservation"@en, "Natural Environment"@en, "Ecosystem"@en, "Climate Change"@en, "Atmosphere"@en, "Clean"@en, "Sustainability"@en ;
    skos:definition "Volunteering addressing environmental conservation, climate change, sustainability, and natural resource protection."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:EthnicMinorities
    a skos:Concept ;
    skos:prefLabel "Ethnic Minorities"@en ;
    skos:altLabel "Ethnic Groups"@en, "Ethnic Communities"@en, "Racial Minorities"@en, "Racial Groups"@en ;
    skos:definition "Volunteering supporting ethnic minority groups, racial equality, and cultural integration."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Families
    a skos:Concept ;
    skos:prefLabel "Families"@en ;
    skos:altLabel "Relatives"@en, "Households"@en, "Family Members"@en, "Loved Ones"@en ;
    skos:definition "Volunteering supporting families, household welfare, and family services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:GenderSexuality
    a skos:Concept ;
    skos:prefLabel "Gender / Sexuality"@en ;
    skos:altLabel "Gender Identity"@en, "Sexual Identity"@en, "Sexual Orientation"@en ;
    skos:definition "Volunteering supporting gender identity, sexual orientation equality, and LGBTIQ+ advocacy."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:GeneralPublic
    a skos:Concept ;
    skos:prefLabel "General Public"@en ;
    skos:altLabel "People"@en, "General Population"@en, "Local Community"@en ;
    skos:definition "Volunteering serving the general public and broader populations."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Health
    a skos:Concept ;
    skos:prefLabel "Health"@en ;
    skos:altLabel "Wellbeing"@en, "Wellness"@en, "Public Health"@en, "Hospital"@en, "Health Service"@en, "Health Providers"@en ;
    skos:definition "Volunteering in healthcare, health promotion, public health, and wellness services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Heritage
    a skos:Concept ;
    skos:prefLabel "Heritage"@en ;
    skos:altLabel "Exhibitions"@en, "Galleries"@en, "History"@en, "Institutions"@en, "Museums"@en ;
    skos:definition "Volunteering in heritage preservation, museums, galleries, historical institutions, and cultural conservation."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Housing
    a skos:Concept ;
    skos:prefLabel "Housing"@en ;
    skos:altLabel "Housing Associations"@en, "Sheltered Housing"@en, "Accommodation"@en, "Displacement"@en, "Homeless People"@en ;
    skos:definition "Volunteering supporting housing provision, homelessness prevention, and accommodation services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Illness
    a skos:Concept ;
    skos:prefLabel "Illness"@en ;
    skos:altLabel "Patients"@en, "Sick People"@en, "Sufferers"@en, "People with Ill Health"@en ;
    skos:definition "Volunteering supporting people with illnesses, patient care, and health condition management."@en ;
    skos:broader :Health ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:InCare
    a skos:Concept ;
    skos:prefLabel "In Care"@en ;
    skos:altLabel "Care Homes"@en, "Hospitalised"@en, "Foster Care"@en, "Existing"@en, "Children Social Care"@en, "Leaving Care"@en ;
    skos:definition "Volunteering in care institutions, care homes, foster care, and supporting those in state care."@en ;
    skos:broader :Care ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LearningDisabilities
    a skos:Concept ;
    skos:prefLabel "Learning Disabilities"@en ;
    skos:altLabel "Learning Difficulties"@en, "Learning Impairment"@en ;
    skos:definition "Volunteering supporting people with learning disabilities and learning difficulties."@en ;
    skos:broader :Disability ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LGBT
    a skos:Concept ;
    skos:prefLabel "LGBT"@en ;
    skos:altLabel "Lesbian"@en, "Gay"@en, "Bisexual"@en, "Transgender"@en, "LGBT Community"@en, "LGBTQ"@en ;
    skos:definition "Volunteering supporting lesbian, gay, bisexual, and transgender communities and LGBTQ+ rights."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LiteracyNeeds
    a skos:Concept ;
    skos:prefLabel "Literacy Needs"@en ;
    skos:altLabel "Literacy Skills"@en, "Literacy Difficulties"@en, "Literacy Support"@en, "Learning"@en, "Training"@en, "Reading"@en, "Writing"@en ;
    skos:definition "Volunteering addressing literacy support, reading and writing development, and literacy skills training."@en ;
    skos:broader :EducationLanguages ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LocalAuthority
    a skos:Concept ;
    skos:prefLabel "Local Authority"@en ;
    skos:altLabel "Local Council"@en, "Local Government"@en, "Council Office"@en, "Town Council"@en ;
    skos:definition "Volunteering with local government, councils, and local authority services."@en ;
    skos:broader :Community ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LocalCommunity
    a skos:Concept ;
    skos:prefLabel "Local Community"@en ;
    skos:altLabel "Neighbourhood"@en, "Community Centres"@en, "Local Population"@en, "Village"@en ;
    skos:definition "Volunteering supporting local community development, neighbourhood initiatives, and village services."@en ;
    skos:broader :Community ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LoneParents
    a skos:Concept ;
    skos:prefLabel "Lone Parents"@en ;
    skos:altLabel "Single Parents"@en, "Single Mothers"@en, "Single Fathers"@en, "One Parent Families"@en, "Single Parent Families"@en ;
    skos:definition "Volunteering supporting single parents, lone parent families, and associated support services."@en ;
    skos:broader :Families ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LowIncomeHouseholds
    a skos:Concept ;
    skos:prefLabel "Low Income Households"@en ;
    skos:altLabel "Family Poverty"@en, "Child Poverty"@en, "Low Earnings"@en ;
    skos:definition "Volunteering addressing low income household support, family poverty, and child poverty reduction."@en ;
    skos:broader :AntiPoverty ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:MensGroups
    a skos:Concept ;
    skos:prefLabel "Mens Groups"@en ;
    skos:altLabel "Mens Support Groups"@en, "Male Peer Support"@en, "Male Groups"@en ;
    skos:definition "Volunteering in men's groups, male peer support, and male-focused community services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:MentalHealth
    a skos:Concept ;
    skos:prefLabel "Mental Health"@en ;
    skos:altLabel "Mental Wellbeing"@en, "Emotional Health"@en, "Psychological Health"@en, "Behavioral Health"@en ;
    skos:definition "Volunteering in mental health support, mental wellbeing, and psychological health services."@en ;
    skos:broader :Health ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:OffendersAndExOffenders
    a skos:Concept ;
    skos:prefLabel "Offenders and Ex-Offenders"@en ;
    skos:altLabel "Prisoners"@en, "Former Offenders"@en, "Offender Rehabilitation"@en, "Criminals"@en ;
    skos:definition "Volunteering with offenders, ex-offenders, prisoners, and offender rehabilitation programmes."@en ;
    skos:broader :CrimeExOffenders ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:OlderPeople
    a skos:Concept ;
    skos:prefLabel "Older People"@en ;
    skos:altLabel "Ageing"@en, "Senior Citizens"@en, "Pensioners"@en, "Old Adults"@en, "Old People"@en, "Elderly"@en, "Old"@en, "Seniors"@en ;
    skos:definition "Volunteering supporting elderly and older people, senior citizens, and age-related services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:OverseasAidDevelopingWorld
    a skos:Concept ;
    skos:prefLabel "Overseas Aid / Developing World"@en ;
    skos:altLabel "Foreign Aid"@en, "International Aid"@en, "Developing Nations"@en, "Developing Economies"@en ;
    skos:definition "Volunteering in international development, overseas aid, and support to developing nations."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Parents
    a skos:Concept ;
    skos:prefLabel "Parents"@en ;
    skos:altLabel "Mothers"@en, "Fathers"@en, "Grandparents"@en, "Foster Parents"@en, "Adoptive Parents"@en ;
    skos:definition "Volunteering supporting parents, parenting support services, and parental care roles."@en ;
    skos:broader :Families ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PhysicalDisability
    a skos:Concept ;
    skos:prefLabel "Physical Disability"@en ;
    skos:altLabel "Physical Impairment"@en ;
    skos:definition "Volunteering supporting people with physical disabilities and physical impairments."@en ;
    skos:broader :Disability ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:RefugeesAsylumSeekers
    a skos:Concept ;
    skos:prefLabel "Refugees / Asylum Seekers"@en ;
    skos:altLabel "Evacuees"@en, "Displaced People"@en, "Migrants"@en ;
    skos:definition "Volunteering supporting refugees, asylum seekers, displaced people, and migrants."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ReligionFaith
    a skos:Concept ;
    skos:prefLabel "Religion & Faith"@en ;
    skos:altLabel "Belief"@en, "Churches"@en, "Religious"@en, "Ideology"@en ;
    skos:definition "Volunteering in religious and faith-based organizations and spiritual community services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ResidentsDisadvantagedNeighbourhoods
    a skos:Concept ;
    skos:prefLabel "Residents of Disadvantaged Neighbourhoods"@en ;
    skos:altLabel "Vulerable groups"@en, "Local Poverty"@en, "Deprived Areas"@en, "Deprived Populations"@en ;
    skos:definition "Volunteering supporting residents of disadvantaged neighbourhoods and deprived communities."@en ;
    skos:broader :LocalCommunity ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SensoryImpairment
    a skos:Concept ;
    skos:prefLabel "Sensory Impairment"@en ;
    skos:altLabel "Hearing Impairment"@en, "Visual Impairment"@en, "Blind and Partially Sighted"@en ;
    skos:definition "Volunteering supporting people with sensory impairments, hearing loss, visual impairment, and blindness."@en ;
    skos:broader :Disability ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SportOutdoorActivities
    a skos:Concept ;
    skos:prefLabel "Sport & Outdoor Activities"@en ;
    skos:altLabel "Sports Clubs"@en, "Outdoor experiences"@en, "Recreation"@en ;
    skos:definition "Volunteering in sports, recreational activities, outdoor experiences, and physical activity promotion."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SubstanceAbuse
    a skos:Concept ;
    skos:prefLabel "Substance Abuse"@en ;
    skos:altLabel "Addiction"@en, "Drug Dependency"@en, "Drugs"@en, "Alcohol Dependency"@en, "Alcohol Issues"@en ;
    skos:definition "Volunteering in addiction support, substance abuse prevention, and recovery services."@en ;
    skos:broader :Health ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Unemployment
    a skos:Concept ;
    skos:prefLabel "Unemployment"@en ;
    skos:altLabel "Job Loss"@en, "Redundancy"@en, "Unemployed People"@en, "Joblessness"@en, "Tackling Unemployment"@en, "Nonemployment"@en, "Unemployed"@en, "Jobless"@en, "Out of work"@en, "Unwaged"@en, "Without Work"@en ;
    skos:definition "Volunteering supporting unemployed people, job training, employment support, and livelihood development."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:VictimsOfCrime
    a skos:Concept ;
    skos:prefLabel "Victims of Crime"@en ;
    skos:altLabel "Victim Support"@en, "Victim Counselling"@en, "Witness Support"@en, "Survivors"@en ;
    skos:definition "Volunteering supporting crime victims, victim advocacy, witness support, and survivor services."@en ;
    skos:broader :CrimeSafety ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WomensGroups
    a skos:Concept ;
    skos:prefLabel "Womens Groups"@en ;
    skos:altLabel "Womens Support Groups"@en, "Female Peer Suport"@en, "Female Groups"@en ;
    skos:definition "Volunteering in women's groups, female peer support, and women-focused community services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:YouthAndChildren
    a skos:Concept ;
    skos:prefLabel "Youth & children"@en ;
    skos:altLabel "Young People and Kids"@en, "Young folks & kids"@en, "Children"@en, "Babies"@en, "Toddlers"@en, "Minors"@en, "Kids"@en, "Infants"@en, "Young People"@en, "Teenagers"@en, "Young Adults"@en, "Youths"@en, "Younger Generation"@en ;
    skos:definition "Volunteering supporting youth development, children's welfare, and young people's services."@en ;
    skos:broader :Cause ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Requirement
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:topConceptOf :Taxonomy ;
    skos:prefLabel "Requirement"@en ;
    skos:definition "Any requirement related to volunteering activities."@en ;
.


## Requirement Category Concepts
### Assets & Equipment Category
:AssetsEquipment
    a skos:Concept ;
    skos:prefLabel "Assets & Equipment"@en ;
    skos:definition "Physical items, equipment, vehicles, and assets needed for volunteering activities."@en ;
    skos:broader :Requirement ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PersonalEquipment
    a skos:Concept ;
    skos:prefLabel "Personal Equipment"@en ;
    skos:definition "Personal protective equipment and personal items for volunteering."@en ;
    skos:broader :AssetsEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SturgyFootwear
    a skos:Concept ;
    skos:prefLabel "Sturdy footwear (e.g., boots)"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WaterproofsWarmLayers
    a skos:Concept ;
    skos:prefLabel "Waterproofs and warm layers"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Gloves
    a skos:Concept ;
    skos:prefLabel "Gloves (work gloves, waterproof gloves)"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:HighVisibilityVest
    a skos:Concept ;
    skos:prefLabel "High-visibility vest"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:HeadtorchFlashlight
    a skos:Concept ;
    skos:prefLabel "Headtorch or flashlight"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PhonePowerBank
    a skos:Concept ;
    skos:prefLabel "Phone + power bank"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:FirstAidKit
    a skos:Concept ;
    skos:prefLabel "Small personal first aid kit"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WaterBottle
    a skos:Concept ;
    skos:prefLabel "Water bottle"@en ;
    skos:broader :PersonalEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:TransportMobilityAssets
    a skos:Concept ;
    skos:prefLabel "Transport & Mobility Assets"@en ;
    skos:definition "Vehicles and transportation capabilities for volunteering."@en ;
    skos:broader :AssetsEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:FourByFourVehicle
    a skos:Concept ;
    skos:prefLabel "4x4 vehicle (personal or organisational)"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SUVOffRoad
    a skos:Concept ;
    skos:prefLabel "SUV or off-road capable vehicle"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:VehicleTowCapability
    a skos:Concept ;
    skos:prefLabel "Vehicle with tow capability"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:VanOrPeopleCarrier
    a skos:Concept ;
    skos:prefLabel "Access to a van or people-carrier"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:TransportEquipmentSupplies
    a skos:Concept ;
    skos:prefLabel "Ability to transport equipment or supplies"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BicyclesCargoBikes
    a skos:Concept ;
    skos:prefLabel "Access to bicycles or cargo bikes"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Boat
    a skos:Concept ;
    skos:prefLabel "Boat"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Hovercraft
    a skos:Concept ;
    skos:prefLabel "Hovercraft"@en ;
    skos:broader :TransportMobilityAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SpecialistUsefulAssets
    a skos:Concept ;
    skos:prefLabel "Specialist or Useful Assets"@en ;
    skos:definition "Specialized tools and equipment for specific volunteering activities."@en ;
    skos:broader :AssetsEquipment ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WalkieTalkiesRadios
    a skos:Concept ;
    skos:prefLabel "Walkie-talkies or radios"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PortableGenerator
    a skos:Concept ;
    skos:prefLabel "Portable generator or power station"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WaterPump
    a skos:Concept ;
    skos:prefLabel "Water pump (for localised flooding help)"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Tools
    a skos:Concept ;
    skos:prefLabel "Tools (shovel, rake, chainsaw, basic toolkit)"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PortableShelterGazebo
    a skos:Concept ;
    skos:prefLabel "Portable shelter/gazebo"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ThermalBlankets
    a skos:Concept ;
    skos:prefLabel "Thermal blankets"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PPE
    a skos:Concept ;
    skos:prefLabel "PPE such as masks, goggles, or waterproof gloves"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:MapsWaterproofMapCases
    a skos:Concept ;
    skos:prefLabel "Maps / waterproof map cases"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LifeJacket
    a skos:Concept ;
    skos:prefLabel "Life jacket (for trained flood volunteers)"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Venue
    a skos:Concept ;
    skos:prefLabel "Venue"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Kitchen
    a skos:Concept ;
    skos:prefLabel "Kitchen"@en ;
    skos:broader :SpecialistUsefulAssets ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

### Community & Environment Knowledge Category
:CommunityEnvironmentKnowledge
    a skos:Concept ;
    skos:prefLabel "Community & Environment Knowledge"@en ;
    skos:definition "Knowledge and awareness of local community, environment, and support systems."@en ;
    skos:broader :Requirement ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LocalRoadsFacilitiesKnowledge
    a skos:Concept ;
    skos:prefLabel "Knowledge of local roads, facilities, and resources"@en ;
    skos:broader :CommunityEnvironmentKnowledge ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:DiverseNeedsAwareness
    a skos:Concept ;
    skos:prefLabel "Understanding diverse needs within the community"@en ;
    skos:broader :CommunityEnvironmentKnowledge ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LocalSupportServicesAwareness
    a skos:Concept ;
    skos:prefLabel "Awareness of local support services"@en ;
    skos:broader :CommunityEnvironmentKnowledge ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

### Legal Category
:Legal
    a skos:Concept ;
    skos:prefLabel "Legal"@en ;
    skos:definition "Legal requirements and compliance checks for volunteering."@en ;
    skos:broader :Requirement ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:IDCheck
    a skos:Concept ;
    skos:prefLabel "ID Check"@en ;
    skos:broader :Legal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:DBSCheck
    a skos:Concept ;
    skos:prefLabel "DBS Check"@en ;
    skos:broader :Legal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

### Physical & Practical Readiness Category
:PhysicalPracticalReadiness
    a skos:Concept ;
    skos:prefLabel "Physical & Practical Readiness"@en ;
    skos:definition "Physical capability and practical preparation requirements for volunteering."@en ;
    skos:broader :Requirement ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PhysicalStamina
    a skos:Concept ;
    skos:prefLabel "Physical stamina for standing, walking, carrying"@en ;
    skos:broader :PhysicalPracticalReadiness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:OutdoorWorkAbility
    a skos:Concept ;
    skos:prefLabel "Ability to work outdoors in varied conditions"@en ;
    skos:broader :PhysicalPracticalReadiness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PersonalPreparedness
    a skos:Concept ;
    skos:prefLabel "Personal preparedness (water, snacks, medication)"@en ;
    skos:broader :PhysicalPracticalReadiness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Reward
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:topConceptOf :Taxonomy ;
    skos:prefLabel "Reward"@en ;
    skos:definition "Any reward related to volunteering activities."@en ;
.

:Skill
    a skos:Concept ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
    skos:topConceptOf :Taxonomy ;
    skos:prefLabel "Skill"@en ;
    skos:definition "Any skill related to volunteering activities."@en ;
.


## Skill Concepts

### Communication
:Communication
    a skos:Concept ;
    skos:prefLabel "Communication"@en ;
    skos:definition "Skills related to verbal, written, and interpersonal communication in volunteering contexts."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ClearSpokenCommunication
    a skos:Concept ;
    skos:prefLabel "Clear spoken communication"@en ;
    skos:definition "Ability to speak clearly and convey information effectively."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ActiveListening
    a skos:Concept ;
    skos:prefLabel "Active listening"@en ;
    skos:definition "Ability to listen attentively and respond appropriately."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:RelayAccurateInformation
    a skos:Concept ;
    skos:prefLabel "Ability to relay accurate information"@en ;
    skos:definition "Ability to pass on information accurately and without distortion."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PhoneOnlineSupport
    a skos:Concept ;
    skos:prefLabel "Supporting people via phone/online"@en ;
    skos:definition "Ability to provide support and assistance remotely via phone or online channels."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:RadioUse
    a skos:Concept ;
    skos:prefLabel "Use of radios / walkie-talkies"@en ;
    skos:definition "Ability to operate radios and walkie-talkies for communication."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PublicEngagement
    a skos:Concept ;
    skos:prefLabel "Confidence engaging with the public or groups"@en ;
    skos:definition "Confidence and ability to engage with members of the public or groups."@en ;
    skos:broader :Communication ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.


### Digital & Technology
:DigitalAndTechnology
    a skos:Concept ;
    skos:prefLabel "Digital & technology"@en ;
    skos:definition "Skills related to digital tools, technology, and IT in volunteering contexts."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BasicITSkills
    a skos:Concept ;
    skos:prefLabel "Basic IT skills"@en ;
    skos:definition "Fundamental computer and information technology skills."@en ;
    skos:broader :DigitalAndTechnology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SmartphoneUse
    a skos:Concept ;
    skos:prefLabel "Confident smartphone use (maps, messaging, camera)"@en ;
    skos:definition "Confident use of smartphone features including maps, messaging, and camera."@en ;
    skos:broader :DigitalAndTechnology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:RemoteCommunicationTools
    a skos:Concept ;
    skos:prefLabel "Familiarity with remote communication tools"@en ;
    skos:definition "Familiarity with video conferencing, messaging platforms, and other remote communication tools."@en ;
    skos:broader :DigitalAndTechnology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:DataEntryAndReporting
    a skos:Concept ;
    skos:prefLabel "Simple data entry and reporting"@en ;
    skos:definition "Ability to perform simple data entry and produce basic reports."@en ;
    skos:broader :DigitalAndTechnology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SocialMediaHandling
    a skos:Concept ;
    skos:prefLabel "Responsible handling of social media"@en ;
    skos:definition "Ability to use social media responsibly and appropriately in a volunteering context."@en ;
    skos:broader :DigitalAndTechnology ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.


### Personal & Interpersonal
:PersonalAndInterpersonal
    a skos:Concept ;
    skos:prefLabel "Personal & interpersonal"@en ;
    skos:definition "Personal qualities and interpersonal skills relevant to volunteering."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:EmpathyAndCompassion
    a skos:Concept ;
    skos:prefLabel "Empathy and compassion"@en ;
    skos:definition "Ability to understand and share the feelings of others with care and concern."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CalmnessUnderPressure
    a skos:Concept ;
    skos:prefLabel "Calmness under pressure"@en ;
    skos:definition "Ability to remain calm and composed in stressful or high-pressure situations."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PatienceAndUnderstanding
    a skos:Concept ;
    skos:prefLabel "Patience and understanding"@en ;
    skos:definition "Ability to be patient and show understanding towards others."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ReliabilityAndTrustworthiness
    a skos:Concept ;
    skos:prefLabel "Reliability and trustworthiness"@en ;
    skos:definition "Being dependable, consistent, and worthy of trust."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ProfessionalBoundaries
    a skos:Concept ;
    skos:prefLabel "Respect for professional boundaries"@en ;
    skos:definition "Ability to maintain appropriate professional boundaries in volunteering relationships."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CulturalSensitivity
    a skos:Concept ;
    skos:prefLabel "Cultural sensitivity"@en ;
    skos:definition "Awareness of and respect for cultural differences and diversity."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:TraumaInformedAwareness
    a skos:Concept ;
    skos:prefLabel "Trauma-informed awareness"@en ;
    skos:definition "Understanding of trauma and its effects, and ability to respond sensitively."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ConflictDeescalation
    a skos:Concept ;
    skos:prefLabel "Conflict de-escalation"@en ;
    skos:definition "Ability to reduce tension and resolve conflicts calmly."@en ;
    skos:broader :PersonalAndInterpersonal ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.


### Practical & Operational
:PracticalAndOperational
    a skos:Concept ;
    skos:prefLabel "Practical & operational"@en ;
    skos:definition "Practical and operational skills for hands-on volunteering tasks."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Logistics
    a skos:Concept ;
    skos:prefLabel "Logistics (sorting, packing, distributing supplies)"@en ;
    skos:definition "Ability to sort, pack, and distribute supplies and materials."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ShelterSupport
    a skos:Concept ;
    skos:prefLabel "Shelter support (setting up spaces, helping evacuees)"@en ;
    skos:definition "Ability to set up shelter spaces and support evacuees or displaced individuals."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BasicRecordKeeping
    a skos:Concept ;
    skos:prefLabel "Basic record keeping"@en ;
    skos:definition "Ability to maintain basic records and documentation."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BasicEquipmentUse
    a skos:Concept ;
    skos:prefLabel "Use of basic equipment (sandbags, barriers, tools)"@en ;
    skos:definition "Ability to use basic equipment such as sandbags, barriers, and hand tools."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:NavigationAndOrientation
    a skos:Concept ;
    skos:prefLabel "Navigation and orientation"@en ;
    skos:definition "Ability to navigate and orient oneself using maps, compasses, or GPS."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:Driving
    a skos:Concept ;
    skos:prefLabel "Driving (car, van, off-road vehicles)"@en ;
    skos:definition "Ability to drive cars, vans, or off-road vehicles."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CrowdQueueManagement
    a skos:Concept ;
    skos:prefLabel "Crowd/queue management"@en ;
    skos:definition "Ability to manage crowds and queues safely and efficiently."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:PilotLicense
    a skos:Concept ;
    skos:prefLabel "Pilot License"@en ;
    skos:definition "Holder of a valid pilot license for aircraft operation."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:HGVCategoryD
    a skos:Concept ;
    skos:prefLabel "HGV/Category D"@en ;
    skos:definition "Holder of an HGV or Category D driving licence for large vehicles."@en ;
    skos:broader :PracticalAndOperational ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.


### Safety & Emergency Awareness
:SafetyAndEmergencyAwareness
    a skos:Concept ;
    skos:prefLabel "Safety & emergency awareness"@en ;
    skos:definition "Skills related to safety procedures and emergency awareness in volunteering contexts."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:EmergencyBriefings
    a skos:Concept ;
    skos:prefLabel "Understanding emergency briefings and instructions"@en ;
    skos:definition "Ability to understand and follow emergency briefings and instructions."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BasicSafeguarding
    a skos:Concept ;
    skos:prefLabel "Basic safeguarding knowledge"@en ;
    skos:definition "Understanding of basic safeguarding principles and practices."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:RiskAwareness
    a skos:Concept ;
    skos:prefLabel "Risk awareness (water, fire, structure, debris)"@en ;
    skos:definition "Awareness of environmental risks including water, fire, structural, and debris hazards."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:SafeManualHandling
    a skos:Concept ;
    skos:prefLabel "Safe manual handling"@en ;
    skos:definition "Knowledge of safe lifting and manual handling techniques."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:IncidentReporting
    a skos:Concept ;
    skos:prefLabel "Incident reporting"@en ;
    skos:definition "Ability to accurately report incidents and safety concerns."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:BasicFirstAid
    a skos:Concept ;
    skos:prefLabel "Basic first aid knowledge"@en ;
    skos:definition "Basic knowledge of first aid procedures and techniques."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:FireSafetyAwareness
    a skos:Concept ;
    skos:prefLabel "Fire safety awareness"@en ;
    skos:definition "Awareness of fire safety procedures and prevention measures."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:WaterSafetyAwareness
    a skos:Concept ;
    skos:prefLabel "Water safety awareness"@en ;
    skos:definition "Awareness of water safety procedures and drowning prevention."@en ;
    skos:broader :SafetyAndEmergencyAwareness ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.


### Teamwork & Leadership
:TeamworkAndLeadership
    a skos:Concept ;
    skos:prefLabel "Teamwork & leadership"@en ;
    skos:definition "Skills related to working in teams and providing leadership in volunteering contexts."@en ;
    skos:broader :Skill ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:CooperativeWork
    a skos:Concept ;
    skos:prefLabel "Ability to work cooperatively"@en ;
    skos:definition "Ability to collaborate and work effectively as part of a team."@en ;
    skos:broader :TeamworkAndLeadership ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:IndependentWork
    a skos:Concept ;
    skos:prefLabel "Ability to work independently"@en ;
    skos:definition "Ability to work autonomously and take initiative without close supervision."@en ;
    skos:broader :TeamworkAndLeadership ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:LeadingSmallGroups
    a skos:Concept ;
    skos:prefLabel "Leading small groups or tasks"@en ;
    skos:definition "Ability to lead small groups of people or manage specific tasks."@en ;
    skos:broader :TeamworkAndLeadership ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:ManagingTeamConflict
    a skos:Concept ;
    skos:prefLabel "Managing conflict within teams"@en ;
    skos:definition "Ability to identify and resolve conflicts within a team setting."@en ;
    skos:broader :TeamworkAndLeadership ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.

:MentoringVolunteers
    a skos:Concept ;
    skos:prefLabel "Supporting or mentoring new volunteers"@en ;
    skos:definition "Ability to support, guide, and mentor new or less experienced volunteers."@en ;
    skos:broader :TeamworkAndLeadership ;
    rdfs:isDefinedBy <https://ns.volunteeringdata.io/> ;
.
}
WHERE {}
