BASE <https://id.volunteeringdata.io/>
PREFIX : <https://ns.volunteeringdata.io/>

CONSTRUCT {
    <Activities> :activities ?activity .
    ?activity :label ?activityLabel .
}
WHERE {
    ?activity :activityLabel ?activityLabel .
}
