name: Full private infra deployment

on:
  workflow_dispatch:

jobs:
  infra-workflow:
    uses: ./.github/workflows/private_infra.yml
  api-workflow:  
    uses: ./.github/workflows/Test_API_CD.yml
      