name: Full private infra deployment

on:
  workflow_dispatch:

jobs:
  infra-workflow:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/private_infra.yml
    secrets: inherit
  api-workflow:  
    needs: infra-workflow
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/Test_API_CD.yml
    secrets: inherit
      