name: Create public infrastructure in Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D41AD83BB7CB4D3A9730E6B1468838E5 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6500D50CB29447A829054748CA8F425 }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./bicep/public.bicep
        failOnStdErr: false